context:
  version: "0.2.2"
package:
  name: pycfast
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pycfast/pycfast-${{ version }}.tar.gz
  sha256: fcbffa485a9656c95576b1dcc39405f575e3f5a8cf419093f273d15135e809a2

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - f90nml >=1.4.5
    - pandas >=2.0.0

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - pycfast
      pip_check: true

about:
  homepage: https://github.com/bewygs/pycfast
  summary: Python interface for building, running, and analyzing CFAST fire simulation models
  documentation: https://pycfast.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bewygs
